# Generated by Django 5.0.6 on 2024-05-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('books', models.ManyToManyField(to='book_orders.book')),
                ('selected_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_orders.class')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='available_classes',
            field=models.ManyToManyField(to='book_orders.class'),
        ),
    ]
