# Generated by Django 5.0.6 on 2024-05-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='selected_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='book_orders.class'),
        ),
    ]
